[package]
version = "2.12.5"
authors = ["Kornel LesinÃÅski <kornel@pngquant.org>"]
build = "rust/build.rs"
categories = ["multimedia::images"]
description = "Convert 24/32-bit images to 8-bit palette with alpha channel.\nBindings for libimagequant that powers pngquant lossy PNG compressor.\n\nDual-licensed like pngquant. See https://pngquant.org for details."
documentation= "https://github.com/kornelski/pngquant#readme"
homepage = "https://pngquant.org"
include = ["/rwpng*", "/pngquant.c", "/rust/*", "/COPYRIGHT", "/Cargo.toml", "/README.md"]
keywords = ["quantization", "palette", "image", "pngquant", "compression"]
license = "GPL-3.0+"
name = "pngquant"
readme = "README.md"
repository = "https://github.com/kornelski/pngquant.git"
edition = "2018"

[[bin]]
name = "pngquant"
path = "rust/bin.rs"

[build-dependencies]
cc = "1.0.38"
dunce = "1.0.0"

[dependencies]
getopts = "0.2.19"
libc = "0.2.60"
libpng-sys = "1.1.5"
wild = "2.0.2"

[dependencies.cocoa_image]
optional = true
version = "1.0.0"

[dependencies.imagequant-sys]
path = "lib"
version = "2.12.5"

[dependencies.lcms2-sys]
optional = true
version = "3.1.1"

[dependencies.openmp-sys]
optional = true
version = "0.1.6"

[features]
cocoa = ["cocoa_image"]
default = ["sse", "lcms2"]
lcms2 = ["lcms2-sys"]
lcms2-static = ["lcms2", "lcms2-sys/static"]
openmp = ["openmp-sys", "imagequant-sys/openmp"]
openmp-static = ["openmp", "openmp-sys/static", "imagequant-sys/openmp-static"]
png-static = ["libpng-sys/static"]
z-static = ["libpng-sys/static-libz"]
static = ["lcms2-static", "png-static", "openmp-static"]
sse = ["imagequant-sys/sse"]
alloc_system = []

[profile.release]
lto = true
